#ifndef GALLERYCORE_GLOBAL_HPP
#define GALLERYCORE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(GALLERYCORE_LIBRARY)
#  define GALLERYCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GALLERYCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GALLERYCORE_GLOBAL_HPP
